name: Specifications
description: ONLY FOR INTERNAL STAFF!
title: "[SPEC] <description>"
labels: ["specs"]
assignees:
  - MatteuSan
body:
  - type: textarea
    id: spec-description
    attributes:
      label: Specification Description
      description: Tell us a bit more about your specification proposal.
    validations:
      required: true
  - type: textarea
    id: spec-context
    attributes:
      label: Specification Context
      description: Why does this matter? Who will benefit from this and in what way?
    validations:
      required: true
  - type: textarea
    id: spec-details
    attributes:
      label: Specification Details
      description: A brief detailing of how the specification will work out.
    validations:
      required: true